spring.application.name=book-social
server.port=8181
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/bookSocial
spring.datasource.username=admin
spring.datasource.password=n/xOMG859
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=testnixomg123@gmail.com
spring.mail.password=ltexccimxocdqeiv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
logging.level.org.springframework.web.socket=DEBUG
logging.level.org.springframework.messaging=DEBUG
#frontend.url=http://localhost:3000
frontend.url=https://tenshiblog.org
stripe.apiKey=sk_test_51QHzwJLtYjGKxtBre6ZrK4KcGQGrrkgkeg9JZFL5E0PSR5OZHScscFkHKwmPulXks7J9C5zaL0LRruWpNnNbRIfJ00pQzg5Z1L